# golangci-lint configuration file
# Documentation: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true                  # линтим *_test.go
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - goconst
    - gocyclo
    - gosec
    - misspell
    - dupl
    - revive
  disable:
    - lll         # Отключение проверки длины строки.
    - unused      # staticcheck уже покрывает unused
  settings:
    gocyclo:
      min-complexity: 15 # Минимальная цикломатическая сложность для предупреждений.
    dupl:
      threshold: 100 # Минимальный размер дублирующегося кода для предупреждений.
    misspell:
      locale: US # Использование американского английского для проверки.
    gosec:
      excludes:
        - G104 # Игнорирование ошибок для пустых возвратов.
    errcheck:
      exclude-functions:
        - io.Copy
        - io.ReadAll
