# golangci-lint configuration file
# Documentation: https://golangci-lint.run/usage/configuration/
version: 2
run:
  go: 1.23.2
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - goconst
    - gocyclo
    - gosec
    - misspell
    - unused
    - dupl
    - revive

  disable:
    - lll # Отключение проверки длины строки.

linters-settings:
  gocyclo:
    min-complexity: 15 # Минимальная цикломатическая сложность для предупреждений.
  dupl:
    threshold: 100 # Минимальный размер дублирующегося кода для предупреждений.
  misspell:
    locale: US # Использование американского английского для проверки.
  gosec:
    exclude:
      - G104 # Игнорирование ошибок для пустых возвратов.
  errcheck:
    exclude-functions:
      - io:Read
      - io:Write

issues:
  exclude-use-default: false # Использовать стандартные исключения.
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo # Исключить gocyclo для тестовых файлов.

output:
  format: colored-line-number # Формат вывода ошибок.
  sort-results: true # Сортировать результаты по файлам.

tests:
  parallel: true # Линтинг тестовых файлов параллельно.
