# golangci-lint configuration file
# Documentation: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - goconst
    - gocyclo
    - gosec
    - misspell
    - unused
    - dupl
    - revive

  disable:
    - lll # Отключение проверки длины строки.

  settings:
    gocyclo:
      min-complexity: 15 # Минимальная цикломатическая сложность для предупреждений.
    dupl:
      threshold: 100 # Минимальный размер дублирующегося кода для предупреждений.
    misspell:
      locale: US # Использование американского английского для проверки.
    gosec:
      excludes:
        - G104 # Игнорирование ошибок для пустых возвратов.
    errcheck:
      exclude-functions:
        - io:Read
        - io:Write

issues:
  max-same-issues: 0               # либо любое другое число

output:
  formats:
    text:
      path: stdout           # Формат вывода ошибок.
      print-linter-name: true
      print-issued-lines: true
      colors: true
