name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

# читаем-только права – меньше поверхностей для атаки
permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    # отменяем предыдущий незавершённый линт для этой ветки
    concurrency:
      group: lint-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      # ставка на версию из go.mod – не придётся править workflow при каждом обновлении
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true          # тот же кеш, что и actions/cache

      - name: Go mod tidy (проверяем, что go.mod/go.sum чистые)
        run: |
          go mod tidy
          git diff --exit-code

      # один вызов action-а: он и скачивает, и запускает golangci-lint
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.0
          args: --timeout=5m
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: false
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false
          install-mode: binary
